package main

var _headerTemplate = `
// Code generated by kratos tool genbts. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated cache proxy package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	{{if .EnableBatch }}"sync"{{end}}
NEWLINE
<<<<<<< HEAD
	"github.com/fever365/kratos/pkg/cache"
	{{if .EnableBatch }}"github.com/fever365/kratos/pkg/sync/errgroup"{{end}}
=======
	"github.com/fever365/kratos/pkg/cache"
	{{if .EnableBatch }}"github.com/fever365/kratos/pkg/sync/errgroup"{{end}}
>>>>>>> 3c6dbc7bf446fcf807931c0adeb03ddb0e59f774
	{{.ImportPackage}}
NEWLINE
	{{if .EnableSingleFlight}}	"golang.org/x/sync/singleflight" {{end}}
)

var (
	_ _bts
)
{{if .EnableSingleFlight}}
var cacheSingleFlights = [SFCOUNT]*singleflight.Group{SFINIT} 
{{end }}
`
