package main

var _headerTemplate = `
// Code generated by kratos tool mcgen. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated mc cache package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	"fmt"
	{{if .UseStrConv}}"strconv"{{end}}
	{{if .EnableBatch }}"sync"{{end}}
NEWLINE
	"github.com/fever365/kratos/pkg/stat/prom"
	{{if .UseMemcached }}"github.com/fever365/kratos/pkg/cache/memcache"{{end}}
	{{if .EnableBatch }}"github.com/fever365/kratos/pkg/sync/errgroup"{{end}}
	"github.com/fever365/kratos/pkg/log"
	{{.ImportPackage}}
)

var _ _mc
`
